/* Generated by Cython 0.9.6.14 on Sun Feb  1 16:14:14 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static char * __pyx_cfilenm= __FILE__;
static char *__pyx_filename;
static char **__pyx_f;

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations */



/* Implementation of bag */


static PyObject *__pyx_n_string;
static PyObject *__pyx_n_sys;
static PyObject *__pyx_n_unittest;
static PyObject *__pyx_n_WhatchaMaDingy;
static PyObject *__pyx_n_TestCase;
static PyObject *__pyx_n_runTest;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_testAlWholeLottaStuff;
static PyObject *__pyx_n___name__;
static PyObject *__pyx_n___main__;
static PyObject *__pyx_n_exit;
static PyObject *__pyx_n_main;

static PyObject *__pyx_builtin___name__;
static PyObject *__pyx_builtin_exit;

/* "/home/erich/doodles/anagrams/python/bag.py":7
 * import unittest
 * 
 * def bag_empty (b):             # <<<<<<<<<<<<<< 
 *     return b == 1
 * 
 */

static PyObject *__pyx_int_1;

static PyObject *__pyx_pf_3bag_bag_empty(PyObject *__pyx_self, PyObject *__pyx_v_b); /*proto*/
static PyObject *__pyx_pf_3bag_bag_empty(PyObject *__pyx_self, PyObject *__pyx_v_b) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":8
 * 
 * def bag_empty (b):
 *     return b == 1             # <<<<<<<<<<<<<< 
 * 
 * def bag (str):
 */
  __pyx_1 = PyObject_RichCompare(__pyx_v_b, __pyx_int_1, Py_EQ); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bag.bag_empty");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/erich/doodles/anagrams/python/bag.py":10
 *     return b == 1
 * 
 * def bag (str):             # <<<<<<<<<<<<<< 
 *     str = string.lower (str)
 *     primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]
 */

static PyObject *__pyx_int_2;
static PyObject *__pyx_int_3;
static PyObject *__pyx_int_5;
static PyObject *__pyx_int_7;
static PyObject *__pyx_int_11;
static PyObject *__pyx_int_13;
static PyObject *__pyx_int_17;
static PyObject *__pyx_int_19;
static PyObject *__pyx_int_23;
static PyObject *__pyx_int_29;
static PyObject *__pyx_int_31;
static PyObject *__pyx_int_37;
static PyObject *__pyx_int_41;
static PyObject *__pyx_int_43;
static PyObject *__pyx_int_47;
static PyObject *__pyx_int_53;
static PyObject *__pyx_int_59;
static PyObject *__pyx_int_61;
static PyObject *__pyx_int_67;
static PyObject *__pyx_int_71;
static PyObject *__pyx_int_73;
static PyObject *__pyx_int_79;
static PyObject *__pyx_int_83;
static PyObject *__pyx_int_89;
static PyObject *__pyx_int_97;
static PyObject *__pyx_int_101;

static PyObject *__pyx_n_lower;
static PyObject *__pyx_n_a;
static PyObject *__pyx_n_z;
static PyObject *__pyx_n_ord;

static PyObject *__pyx_builtin_ord;


static PyObject *__pyx_pf_3bag_bag(PyObject *__pyx_self, PyObject *__pyx_v_str); /*proto*/
static PyObject *__pyx_pf_3bag_bag(PyObject *__pyx_self, PyObject *__pyx_v_str) {
  PyObject *__pyx_v_primes;
  PyObject *__pyx_v_rv;
  PyObject *__pyx_v_c;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_ssize_t __pyx_4 = 0;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  Py_INCREF(__pyx_v_str);
  __pyx_v_primes = Py_None; Py_INCREF(Py_None);
  __pyx_v_rv = Py_None; Py_INCREF(Py_None);
  __pyx_v_c = Py_None; Py_INCREF(Py_None);

  /* "/home/erich/doodles/anagrams/python/bag.py":11
 * 
 * def bag (str):
 *     str = string.lower (str)             # <<<<<<<<<<<<<< 
 *     primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]
 *     rv = 1
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_string); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_lower); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_str);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_str);
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  Py_DECREF(__pyx_v_str);
  __pyx_v_str = __pyx_3;
  __pyx_3 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":12
 * def bag (str):
 *     str = string.lower (str)
 *     primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]             # <<<<<<<<<<<<<< 
 *     rv = 1
 * 
 */
  __pyx_2 = PyList_New(26); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_int_2);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_int_2);
  Py_INCREF(__pyx_int_3);
  PyList_SET_ITEM(__pyx_2, 1, __pyx_int_3);
  Py_INCREF(__pyx_int_5);
  PyList_SET_ITEM(__pyx_2, 2, __pyx_int_5);
  Py_INCREF(__pyx_int_7);
  PyList_SET_ITEM(__pyx_2, 3, __pyx_int_7);
  Py_INCREF(__pyx_int_11);
  PyList_SET_ITEM(__pyx_2, 4, __pyx_int_11);
  Py_INCREF(__pyx_int_13);
  PyList_SET_ITEM(__pyx_2, 5, __pyx_int_13);
  Py_INCREF(__pyx_int_17);
  PyList_SET_ITEM(__pyx_2, 6, __pyx_int_17);
  Py_INCREF(__pyx_int_19);
  PyList_SET_ITEM(__pyx_2, 7, __pyx_int_19);
  Py_INCREF(__pyx_int_23);
  PyList_SET_ITEM(__pyx_2, 8, __pyx_int_23);
  Py_INCREF(__pyx_int_29);
  PyList_SET_ITEM(__pyx_2, 9, __pyx_int_29);
  Py_INCREF(__pyx_int_31);
  PyList_SET_ITEM(__pyx_2, 10, __pyx_int_31);
  Py_INCREF(__pyx_int_37);
  PyList_SET_ITEM(__pyx_2, 11, __pyx_int_37);
  Py_INCREF(__pyx_int_41);
  PyList_SET_ITEM(__pyx_2, 12, __pyx_int_41);
  Py_INCREF(__pyx_int_43);
  PyList_SET_ITEM(__pyx_2, 13, __pyx_int_43);
  Py_INCREF(__pyx_int_47);
  PyList_SET_ITEM(__pyx_2, 14, __pyx_int_47);
  Py_INCREF(__pyx_int_53);
  PyList_SET_ITEM(__pyx_2, 15, __pyx_int_53);
  Py_INCREF(__pyx_int_59);
  PyList_SET_ITEM(__pyx_2, 16, __pyx_int_59);
  Py_INCREF(__pyx_int_61);
  PyList_SET_ITEM(__pyx_2, 17, __pyx_int_61);
  Py_INCREF(__pyx_int_67);
  PyList_SET_ITEM(__pyx_2, 18, __pyx_int_67);
  Py_INCREF(__pyx_int_71);
  PyList_SET_ITEM(__pyx_2, 19, __pyx_int_71);
  Py_INCREF(__pyx_int_73);
  PyList_SET_ITEM(__pyx_2, 20, __pyx_int_73);
  Py_INCREF(__pyx_int_79);
  PyList_SET_ITEM(__pyx_2, 21, __pyx_int_79);
  Py_INCREF(__pyx_int_83);
  PyList_SET_ITEM(__pyx_2, 22, __pyx_int_83);
  Py_INCREF(__pyx_int_89);
  PyList_SET_ITEM(__pyx_2, 23, __pyx_int_89);
  Py_INCREF(__pyx_int_97);
  PyList_SET_ITEM(__pyx_2, 24, __pyx_int_97);
  Py_INCREF(__pyx_int_101);
  PyList_SET_ITEM(__pyx_2, 25, __pyx_int_101);
  Py_DECREF(__pyx_v_primes);
  __pyx_v_primes = ((PyObject *)__pyx_2);
  __pyx_2 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":13
 *     str = string.lower (str)
 *     primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]
 *     rv = 1             # <<<<<<<<<<<<<< 
 * 
 *     for c in str:
 */
  Py_INCREF(__pyx_int_1);
  Py_DECREF(__pyx_v_rv);
  __pyx_v_rv = __pyx_int_1;

  /* "/home/erich/doodles/anagrams/python/bag.py":15
 *     rv = 1
 * 
 *     for c in str:             # <<<<<<<<<<<<<< 
 *         if (c >= 'a') and (c <= 'z'):
 *             rv *= primes [ord (c) - ord ('a')]
 */
  if (PyList_CheckExact(__pyx_v_str)) { __pyx_4 = 0; __pyx_1 = __pyx_v_str; Py_INCREF(__pyx_1); }
  else { __pyx_1 = PyObject_GetIter(__pyx_v_str); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  for (;;) {
    if (PyList_CheckExact(__pyx_1)) { if (__pyx_4 >= PyList_GET_SIZE(__pyx_1)) break; __pyx_3 = PyList_GET_ITEM(__pyx_1, __pyx_4++); Py_INCREF(__pyx_3); }
    else {
      __pyx_3 = PyIter_Next(__pyx_1);
      if (!__pyx_3) {
        break;
      }
    }
    Py_DECREF(__pyx_v_c);
    __pyx_v_c = __pyx_3;
    __pyx_3 = 0;

    /* "/home/erich/doodles/anagrams/python/bag.py":16
 * 
 *     for c in str:
 *         if (c >= 'a') and (c <= 'z'):             # <<<<<<<<<<<<<< 
 *             rv *= primes [ord (c) - ord ('a')]
 * 
 */
    __pyx_2 = PyObject_RichCompare(__pyx_v_c, __pyx_n_a, Py_GE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_5 = __Pyx_PyObject_IsTrue(__pyx_2); if (unlikely(__pyx_5 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
    if (__pyx_5) {
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = PyObject_RichCompare(__pyx_v_c, __pyx_n_z, Py_LE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
    }
    __pyx_5 = __Pyx_PyObject_IsTrue(__pyx_2); if (unlikely(__pyx_5 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__pyx_5) {

      /* "/home/erich/doodles/anagrams/python/bag.py":17
 *     for c in str:
 *         if (c >= 'a') and (c <= 'z'):
 *             rv *= primes [ord (c) - ord ('a')]             # <<<<<<<<<<<<<< 
 * 
 *     return rv
 */
      __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_INCREF(__pyx_v_c);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_c);
      __pyx_6 = PyObject_Call(__pyx_builtin_ord, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
      __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_INCREF(__pyx_n_a);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_a);
      __pyx_7 = PyObject_Call(__pyx_builtin_ord, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
      __pyx_2 = PyNumber_Subtract(__pyx_6, __pyx_7); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      __pyx_6 = PyObject_GetItem(__pyx_v_primes, __pyx_2); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_3 = PyNumber_InPlaceMultiply(__pyx_v_rv, __pyx_6); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_v_rv);
      __pyx_v_rv = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":19
 *             rv *= primes [ord (c) - ord ('a')]
 * 
 *     return rv             # <<<<<<<<<<<<<< 
 * 
 * def bags_equal (s1, s2):
 */
  Py_INCREF(__pyx_v_rv);
  __pyx_r = __pyx_v_rv;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("bag.bag");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_primes);
  Py_DECREF(__pyx_v_rv);
  Py_DECREF(__pyx_v_c);
  Py_DECREF(__pyx_v_str);
  return __pyx_r;
}

/* "/home/erich/doodles/anagrams/python/bag.py":21
 *     return rv
 * 
 * def bags_equal (s1, s2):             # <<<<<<<<<<<<<< 
 *     return s1 == s2
 * 
 */

static PyObject *__pyx_pf_3bag_bags_equal(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_3bag_bags_equal(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_s1 = 0;
  PyObject *__pyx_v_s2 = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"s1","s2",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_s1 = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_s2 = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_s1, &__pyx_v_s2))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("bag.bags_equal");
  return NULL;
  __pyx_L3:;

  /* "/home/erich/doodles/anagrams/python/bag.py":22
 * 
 * def bags_equal (s1, s2):
 *     return s1 == s2             # <<<<<<<<<<<<<< 
 * 
 * def subtract_bags (b1, b2):
 */
  __pyx_1 = PyObject_RichCompare(__pyx_v_s1, __pyx_v_s2, Py_EQ); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bag.bags_equal");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/erich/doodles/anagrams/python/bag.py":24
 *     return s1 == s2
 * 
 * def subtract_bags (b1, b2):             # <<<<<<<<<<<<<< 
 *     quotient  = b1 / b2
 *     remainder = b1 % b2
 */

static PyObject *__pyx_int_0;

static PyObject *__pyx_pf_3bag_subtract_bags(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_3bag_subtract_bags(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_b1 = 0;
  PyObject *__pyx_v_b2 = 0;
  PyObject *__pyx_v_quotient;
  PyObject *__pyx_v_remainder;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  static char *__pyx_argnames[] = {"b1","b2",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_b1 = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_b2 = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_b1, &__pyx_v_b2))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("bag.subtract_bags");
  return NULL;
  __pyx_L3:;
  __pyx_v_quotient = Py_None; Py_INCREF(Py_None);
  __pyx_v_remainder = Py_None; Py_INCREF(Py_None);

  /* "/home/erich/doodles/anagrams/python/bag.py":25
 * 
 * def subtract_bags (b1, b2):
 *     quotient  = b1 / b2             # <<<<<<<<<<<<<< 
 *     remainder = b1 % b2
 *     if (0 == remainder):
 */
  __pyx_1 = PyNumber_Divide(__pyx_v_b1, __pyx_v_b2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_quotient);
  __pyx_v_quotient = __pyx_1;
  __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":26
 * def subtract_bags (b1, b2):
 *     quotient  = b1 / b2
 *     remainder = b1 % b2             # <<<<<<<<<<<<<< 
 *     if (0 == remainder):
 *         return quotient
 */
  __pyx_1 = PyNumber_Remainder(__pyx_v_b1, __pyx_v_b2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_remainder);
  __pyx_v_remainder = __pyx_1;
  __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":27
 *     quotient  = b1 / b2
 *     remainder = b1 % b2
 *     if (0 == remainder):             # <<<<<<<<<<<<<< 
 *         return quotient
 *     else:
 */
  __pyx_1 = PyObject_RichCompare(__pyx_int_0, __pyx_v_remainder, Py_EQ); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_1); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {

    /* "/home/erich/doodles/anagrams/python/bag.py":28
 *     remainder = b1 % b2
 *     if (0 == remainder):
 *         return quotient             # <<<<<<<<<<<<<< 
 *     else:
 *         return 0
 */
    Py_INCREF(__pyx_v_quotient);
    __pyx_r = __pyx_v_quotient;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/home/erich/doodles/anagrams/python/bag.py":30
 *         return quotient
 *     else:
 *         return 0             # <<<<<<<<<<<<<< 
 * 
 * class WhatchaMaDingy (unittest.TestCase):
 */
    Py_INCREF(__pyx_int_0);
    __pyx_r = __pyx_int_0;
    goto __pyx_L0;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bag.subtract_bags");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_quotient);
  Py_DECREF(__pyx_v_remainder);
  return __pyx_r;
}

/* "/home/erich/doodles/anagrams/python/bag.py":33
 * 
 * class WhatchaMaDingy (unittest.TestCase):
 *     def __init__ (self, methodName='runTest'):             # <<<<<<<<<<<<<< 
 *         self.done = False
 *         unittest.TestCase.__init__ (self, methodName)
 */

static PyObject *__pyx_n_done;

static PyObject *__pyx_pf_3bag_14WhatchaMaDingy___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_3bag_14WhatchaMaDingy___init__ = {"__init__", (PyCFunction)__pyx_pf_3bag_14WhatchaMaDingy___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_pf_3bag_14WhatchaMaDingy___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_methodName = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"self","methodName",0};
  __pyx_v_methodName = __pyx_n_runTest;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_self = PyTuple_GET_ITEM(__pyx_args, 0);
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_methodName = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_self, &__pyx_v_methodName))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("bag.WhatchaMaDingy.__init__");
  return NULL;
  __pyx_L3:;

  /* "/home/erich/doodles/anagrams/python/bag.py":34
 * class WhatchaMaDingy (unittest.TestCase):
 *     def __init__ (self, methodName='runTest'):
 *         self.done = False             # <<<<<<<<<<<<<< 
 *         unittest.TestCase.__init__ (self, methodName)
 * 
 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_done, Py_False) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/home/erich/doodles/anagrams/python/bag.py":35
 *     def __init__ (self, methodName='runTest'):
 *         self.done = False
 *         unittest.TestCase.__init__ (self, methodName)             # <<<<<<<<<<<<<< 
 * 
 *     def testAlWholeLottaStuff (self):
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_unittest); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_TestCase); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n___init__); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_self);
  Py_INCREF(__pyx_v_methodName);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_methodName);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bag.WhatchaMaDingy.__init__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/erich/doodles/anagrams/python/bag.py":37
 *         unittest.TestCase.__init__ (self, methodName)
 * 
 *     def testAlWholeLottaStuff (self):             # <<<<<<<<<<<<<< 
 *         self.assert_ (bag_empty (bag ("")))
 * 
 */

static PyObject *__pyx_n_assert_;
static PyObject *__pyx_n_bag_empty;
static PyObject *__pyx_n_bag;
static PyObject *__pyx_n_bags_equal;
static PyObject *__pyx_n_abc;
static PyObject *__pyx_n_cba;
static PyObject *__pyx_n_bc;
static PyObject *__pyx_n_subtract_bags;
static PyObject *__pyx_n_ab;
static PyObject *__pyx_n_b;
static PyObject *__pyx_n_aa;
static PyObject *__pyx_n_x;
static PyObject *__pyx_n_ABC;

static PyObject *__pyx_k_10p;
static PyObject *__pyx_k_23p;

static char __pyx_k_10[] = "";
static char __pyx_k_23[] = "When first I was a wee, wee lad\n        Eating on my horse\n        I had to take a farting duck\n        Much to my remorse.\n        Oh Sally can't you hear my plea\n        When Roe V Wade is nigh\n        And candles slide the misty morn\n        With dimples on your tie.";

static PyObject *__pyx_pf_3bag_14WhatchaMaDingy_testAlWholeLottaStuff(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_3bag_14WhatchaMaDingy_testAlWholeLottaStuff = {"testAlWholeLottaStuff", (PyCFunction)__pyx_pf_3bag_14WhatchaMaDingy_testAlWholeLottaStuff, METH_O, 0};
static PyObject *__pyx_pf_3bag_14WhatchaMaDingy_testAlWholeLottaStuff(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_v_silly_long_string;
  PyObject *__pyx_v_ever_so_slightly_longer_string;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  __pyx_v_silly_long_string = Py_None; Py_INCREF(Py_None);
  __pyx_v_ever_so_slightly_longer_string = Py_None; Py_INCREF(Py_None);

  /* "/home/erich/doodles/anagrams/python/bag.py":38
 * 
 *     def testAlWholeLottaStuff (self):
 *         self.assert_ (bag_empty (bag ("")))             # <<<<<<<<<<<<<< 
 * 
 *         self.assert_ (not (bag_empty (bag ("a"))))
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_bag_empty); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_k_10p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k_10p);
  __pyx_5 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_5);
  __pyx_5 = 0;
  __pyx_4 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":40
 *         self.assert_ (bag_empty (bag ("")))
 * 
 *         self.assert_ (not (bag_empty (bag ("a"))))             # <<<<<<<<<<<<<< 
 * 
 *         self.assert_ (bags_equal (bag ("abc"),
 */
  __pyx_3 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bag_empty); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_a);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_n_a);
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_5 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_6 = __Pyx_PyObject_IsTrue(__pyx_5); if (unlikely(__pyx_6 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_2 = __Pyx_PyBool_FromLong((!__pyx_6)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_1 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":42
 *         self.assert_ (not (bag_empty (bag ("a"))))
 * 
 *         self.assert_ (bags_equal (bag ("abc"),             # <<<<<<<<<<<<<< 
 *                             bag ("cba")))
 * 
 */
  __pyx_5 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_bags_equal); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_abc);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_n_abc);
  __pyx_1 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":43
 * 
 *         self.assert_ (bags_equal (bag ("abc"),
 *                             bag ("cba")))             # <<<<<<<<<<<<<< 
 * 
 *         self.assert_ (not (bags_equal (bag ("abc"),
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_cba);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_n_cba);
  __pyx_7 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_3 = PyTuple_New(2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_7);
  __pyx_1 = 0;
  __pyx_7 = 0;
  __pyx_4 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_7 = PyObject_Call(__pyx_5, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":45
 *                             bag ("cba")))
 * 
 *         self.assert_ (not (bags_equal (bag ("abc"),             # <<<<<<<<<<<<<< 
 *                                  bag ("bc"))))
 * 
 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_bags_equal); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_abc);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_n_abc);
  __pyx_1 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":46
 * 
 *         self.assert_ (not (bags_equal (bag ("abc"),
 *                                  bag ("bc"))))             # <<<<<<<<<<<<<< 
 * 
 *         self.assert_ (bags_equal (bag ("a"),
 */
  __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_bc);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_n_bc);
  __pyx_5 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_7 = PyTuple_New(2); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_7, 1, __pyx_5);
  __pyx_1 = 0;
  __pyx_5 = 0;
  __pyx_4 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_7), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_7)); __pyx_7 = 0;
  __pyx_6 = __Pyx_PyObject_IsTrue(__pyx_4); if (unlikely(__pyx_6 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_1 = __Pyx_PyBool_FromLong((!__pyx_6)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":48
 *                                  bag ("bc"))))
 * 
 *         self.assert_ (bags_equal (bag ("a"),             # <<<<<<<<<<<<<< 
 *                               subtract_bags (bag("ab"),
 *                                              bag ("b"))))
 */
  __pyx_7 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bags_equal); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_a);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_a);
  __pyx_5 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":49
 * 
 *         self.assert_ (bags_equal (bag ("a"),
 *                               subtract_bags (bag("ab"),             # <<<<<<<<<<<<<< 
 *                                              bag ("b"))))
 *         self.assert_ (not (subtract_bags (bag ("a"),
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_subtract_bags); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_ab);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_ab);
  __pyx_8 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":50
 *         self.assert_ (bags_equal (bag ("a"),
 *                               subtract_bags (bag("ab"),
 *                                              bag ("b"))))             # <<<<<<<<<<<<<< 
 *         self.assert_ (not (subtract_bags (bag ("a"),
 *                                     bag ("b"))))
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_b);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_b);
  __pyx_9 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_8);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_9);
  __pyx_8 = 0;
  __pyx_9 = 0;
  __pyx_2 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_8 = PyTuple_New(2); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_8, 0, __pyx_5);
  PyTuple_SET_ITEM(__pyx_8, 1, __pyx_2);
  __pyx_5 = 0;
  __pyx_2 = 0;
  __pyx_9 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_8), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_8)); __pyx_8 = 0;
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_9);
  __pyx_9 = 0;
  __pyx_1 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":51
 *                               subtract_bags (bag("ab"),
 *                                              bag ("b"))))
 *         self.assert_ (not (subtract_bags (bag ("a"),             # <<<<<<<<<<<<<< 
 *                                     bag ("b"))))
 * 
 */
  __pyx_5 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_subtract_bags); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_8 = PyTuple_New(1); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_a);
  PyTuple_SET_ITEM(__pyx_8, 0, __pyx_n_a);
  __pyx_9 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_8), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_8)); __pyx_8 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":52
 *                                              bag ("b"))))
 *         self.assert_ (not (subtract_bags (bag ("a"),
 *                                     bag ("b"))))             # <<<<<<<<<<<<<< 
 * 
 *         self.assert_ (not (subtract_bags (bag ("a"),
 */
  __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_b);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_b);
  __pyx_1 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_9);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  __pyx_9 = 0;
  __pyx_1 = 0;
  __pyx_8 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_6 = __Pyx_PyObject_IsTrue(__pyx_8); if (unlikely(__pyx_6 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_8); __pyx_8 = 0;
  __pyx_7 = __Pyx_PyBool_FromLong((!__pyx_6)); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_7);
  __pyx_7 = 0;
  __pyx_9 = PyObject_Call(__pyx_5, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_9); __pyx_9 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":54
 *                                     bag ("b"))))
 * 
 *         self.assert_ (not (subtract_bags (bag ("a"),             # <<<<<<<<<<<<<< 
 *                                     bag ("aa"))))
 * 
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_subtract_bags); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_8 = PyTuple_New(1); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_a);
  PyTuple_SET_ITEM(__pyx_8, 0, __pyx_n_a);
  __pyx_7 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_8), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_8)); __pyx_8 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":55
 * 
 *         self.assert_ (not (subtract_bags (bag ("a"),
 *                                     bag ("aa"))))             # <<<<<<<<<<<<<< 
 * 
 *         silly_long_string = "When first I was a wee, wee lad\n\
 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_aa);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_aa);
  __pyx_9 = PyObject_Call(__pyx_5, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_7);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_9);
  __pyx_7 = 0;
  __pyx_9 = 0;
  __pyx_8 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_6 = __Pyx_PyObject_IsTrue(__pyx_8); if (unlikely(__pyx_6 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_8); __pyx_8 = 0;
  __pyx_5 = __Pyx_PyBool_FromLong((!__pyx_6)); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_5);
  __pyx_5 = 0;
  __pyx_7 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":57
 *                                     bag ("aa"))))
 * 
 *         silly_long_string = "When first I was a wee, wee lad\n\             # <<<<<<<<<<<<<< 
 *         Eating on my horse\n\
 *         I had to take a farting duck\n\
 */
  Py_INCREF(__pyx_k_23p);
  Py_DECREF(__pyx_v_silly_long_string);
  __pyx_v_silly_long_string = __pyx_k_23p;

  /* "/home/erich/doodles/anagrams/python/bag.py":66
 *         With dimples on your tie."
 * 
 *         ever_so_slightly_longer_string = silly_long_string + "x"             # <<<<<<<<<<<<<< 
 *         self.assert_ (bags_equal (bag ("x"),
 *                             subtract_bags (bag (ever_so_slightly_longer_string),
 */
  __pyx_9 = PyNumber_Add(__pyx_v_silly_long_string, __pyx_n_x); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_ever_so_slightly_longer_string);
  __pyx_v_ever_so_slightly_longer_string = __pyx_9;
  __pyx_9 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":67
 * 
 *         ever_so_slightly_longer_string = silly_long_string + "x"
 *         self.assert_ (bags_equal (bag ("x"),             # <<<<<<<<<<<<<< 
 *                             subtract_bags (bag (ever_so_slightly_longer_string),
 *                                            bag (silly_long_string))))
 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bags_equal); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_8 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_x);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_n_x);
  __pyx_1 = PyObject_Call(__pyx_8, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_8); __pyx_8 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":68
 *         ever_so_slightly_longer_string = silly_long_string + "x"
 *         self.assert_ (bags_equal (bag ("x"),
 *                             subtract_bags (bag (ever_so_slightly_longer_string),             # <<<<<<<<<<<<<< 
 *                                            bag (silly_long_string))))
 * 
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_subtract_bags); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_9 = PyTuple_New(1); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_ever_so_slightly_longer_string);
  PyTuple_SET_ITEM(__pyx_9, 0, __pyx_v_ever_so_slightly_longer_string);
  __pyx_8 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_9), NULL); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(((PyObject *)__pyx_9)); __pyx_9 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":69
 *         self.assert_ (bags_equal (bag ("x"),
 *                             subtract_bags (bag (ever_so_slightly_longer_string),
 *                                            bag (silly_long_string))))             # <<<<<<<<<<<<<< 
 * 
 *         self.assert_ (bags_equal (bag ("abc"),
 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(1); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_silly_long_string);
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_v_silly_long_string);
  __pyx_9 = PyObject_Call(__pyx_5, ((PyObject *)__pyx_7), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(((PyObject *)__pyx_7)); __pyx_7 = 0;
  __pyx_5 = PyTuple_New(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_8);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_9);
  __pyx_8 = 0;
  __pyx_9 = 0;
  __pyx_7 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  __pyx_8 = PyTuple_New(2); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_8, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_8, 1, __pyx_7);
  __pyx_1 = 0;
  __pyx_7 = 0;
  __pyx_9 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_8), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_8)); __pyx_8 = 0;
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_9);
  __pyx_9 = 0;
  __pyx_5 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":71
 *                                            bag (silly_long_string))))
 * 
 *         self.assert_ (bags_equal (bag ("abc"),             # <<<<<<<<<<<<<< 
 *                             bag ("ABC")))
 * 
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_assert_); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_bags_equal); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_8 = PyTuple_New(1); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_abc);
  PyTuple_SET_ITEM(__pyx_8, 0, __pyx_n_abc);
  __pyx_9 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_8), NULL); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_8)); __pyx_8 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":72
 * 
 *         self.assert_ (bags_equal (bag ("abc"),
 *                             bag ("ABC")))             # <<<<<<<<<<<<<< 
 * 
 *         self.done = True;
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_bag); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_ABC);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_ABC);
  __pyx_5 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_9);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_9 = 0;
  __pyx_5 = 0;
  __pyx_8 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_8);
  __pyx_8 = 0;
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":74
 *                             bag ("ABC")))
 * 
 *         self.done = True;             # <<<<<<<<<<<<<< 
 * 
 * if __name__ == "__main__":
 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_done, Py_True) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  __Pyx_AddTraceback("bag.WhatchaMaDingy.testAlWholeLottaStuff");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_silly_long_string);
  Py_DECREF(__pyx_v_ever_so_slightly_longer_string);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_ABC, "ABC"},
  {&__pyx_n_TestCase, "TestCase"},
  {&__pyx_n_WhatchaMaDingy, "WhatchaMaDingy"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n___main__, "__main__"},
  {&__pyx_n___name__, "__name__"},
  {&__pyx_n_a, "a"},
  {&__pyx_n_aa, "aa"},
  {&__pyx_n_ab, "ab"},
  {&__pyx_n_abc, "abc"},
  {&__pyx_n_assert_, "assert_"},
  {&__pyx_n_b, "b"},
  {&__pyx_n_bag, "bag"},
  {&__pyx_n_bag_empty, "bag_empty"},
  {&__pyx_n_bags_equal, "bags_equal"},
  {&__pyx_n_bc, "bc"},
  {&__pyx_n_cba, "cba"},
  {&__pyx_n_done, "done"},
  {&__pyx_n_exit, "exit"},
  {&__pyx_n_lower, "lower"},
  {&__pyx_n_main, "main"},
  {&__pyx_n_ord, "ord"},
  {&__pyx_n_runTest, "runTest"},
  {&__pyx_n_string, "string"},
  {&__pyx_n_subtract_bags, "subtract_bags"},
  {&__pyx_n_sys, "sys"},
  {&__pyx_n_testAlWholeLottaStuff, "testAlWholeLottaStuff"},
  {&__pyx_n_unittest, "unittest"},
  {&__pyx_n_x, "x"},
  {&__pyx_n_z, "z"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k_10p, __pyx_k_10, sizeof(__pyx_k_10), 0},
  {&__pyx_k_23p, __pyx_k_23, sizeof(__pyx_k_23), 0},
  {0, 0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"bag_empty", (PyCFunction)__pyx_pf_3bag_bag_empty, METH_O, 0},
  {"bag", (PyCFunction)__pyx_pf_3bag_bag, METH_O, 0},
  {"bags_equal", (PyCFunction)__pyx_pf_3bag_bags_equal, METH_VARARGS|METH_KEYWORDS, 0},
  {"subtract_bags", (PyCFunction)__pyx_pf_3bag_subtract_bags, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initbag(void); /*proto*/
PyMODINIT_FUNC initbag(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("bag", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  __pyx_int_1 = PyInt_FromLong(1); if (unlikely(!__pyx_int_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_2 = PyInt_FromLong(2); if (unlikely(!__pyx_int_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_3 = PyInt_FromLong(3); if (unlikely(!__pyx_int_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_5 = PyInt_FromLong(5); if (unlikely(!__pyx_int_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_7 = PyInt_FromLong(7); if (unlikely(!__pyx_int_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_11 = PyInt_FromLong(11); if (unlikely(!__pyx_int_11)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_13 = PyInt_FromLong(13); if (unlikely(!__pyx_int_13)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_17 = PyInt_FromLong(17); if (unlikely(!__pyx_int_17)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_19 = PyInt_FromLong(19); if (unlikely(!__pyx_int_19)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_23 = PyInt_FromLong(23); if (unlikely(!__pyx_int_23)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_29 = PyInt_FromLong(29); if (unlikely(!__pyx_int_29)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_31 = PyInt_FromLong(31); if (unlikely(!__pyx_int_31)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_37 = PyInt_FromLong(37); if (unlikely(!__pyx_int_37)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_41 = PyInt_FromLong(41); if (unlikely(!__pyx_int_41)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_43 = PyInt_FromLong(43); if (unlikely(!__pyx_int_43)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_47 = PyInt_FromLong(47); if (unlikely(!__pyx_int_47)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_53 = PyInt_FromLong(53); if (unlikely(!__pyx_int_53)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_59 = PyInt_FromLong(59); if (unlikely(!__pyx_int_59)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_61 = PyInt_FromLong(61); if (unlikely(!__pyx_int_61)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_67 = PyInt_FromLong(67); if (unlikely(!__pyx_int_67)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_71 = PyInt_FromLong(71); if (unlikely(!__pyx_int_71)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_73 = PyInt_FromLong(73); if (unlikely(!__pyx_int_73)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_79 = PyInt_FromLong(79); if (unlikely(!__pyx_int_79)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_83 = PyInt_FromLong(83); if (unlikely(!__pyx_int_83)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_89 = PyInt_FromLong(89); if (unlikely(!__pyx_int_89)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_97 = PyInt_FromLong(97); if (unlikely(!__pyx_int_97)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_101 = PyInt_FromLong(101); if (unlikely(!__pyx_int_101)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_builtin___name__ = __Pyx_GetName(__pyx_b, __pyx_n___name__); if (!__pyx_builtin___name__) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_builtin_exit = __Pyx_GetName(__pyx_b, __pyx_n_exit); if (!__pyx_builtin_exit) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_builtin_ord = __Pyx_GetName(__pyx_b, __pyx_n_ord); if (!__pyx_builtin_ord) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/home/erich/doodles/anagrams/python/bag.py":3
 * #!/usr/bin/env python
 * 
 * import string             # <<<<<<<<<<<<<< 
 * import sys
 * import unittest
 */
  __pyx_1 = __Pyx_Import(__pyx_n_string, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_string, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":4
 * 
 * import string
 * import sys             # <<<<<<<<<<<<<< 
 * import unittest
 * 
 */
  __pyx_1 = __Pyx_Import(__pyx_n_sys, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":5
 * import string
 * import sys
 * import unittest             # <<<<<<<<<<<<<< 
 * 
 * def bag_empty (b):
 */
  __pyx_1 = __Pyx_Import(__pyx_n_unittest, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_unittest, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":32
 *         return 0
 * 
 * class WhatchaMaDingy (unittest.TestCase):             # <<<<<<<<<<<<<< 
 *     def __init__ (self, methodName='runTest'):
 *         self.done = False
 */
  __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_unittest); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_TestCase); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = __Pyx_CreateClass(((PyObject *)__pyx_2), ((PyObject *)__pyx_1), __pyx_n_WhatchaMaDingy, "bag"); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":33
 * 
 * class WhatchaMaDingy (unittest.TestCase):
 *     def __init__ (self, methodName='runTest'):             # <<<<<<<<<<<<<< 
 *         self.done = False
 *         unittest.TestCase.__init__ (self, methodName)
 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_3bag_14WhatchaMaDingy___init__, 0); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":37
 *         unittest.TestCase.__init__ (self, methodName)
 * 
 *     def testAlWholeLottaStuff (self):             # <<<<<<<<<<<<<< 
 *         self.assert_ (bag_empty (bag ("")))
 * 
 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_3bag_14WhatchaMaDingy_testAlWholeLottaStuff, 0); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_testAlWholeLottaStuff, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_WhatchaMaDingy, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;

  /* "/home/erich/doodles/anagrams/python/bag.py":76
 *         self.done = True;
 * 
 * if __name__ == "__main__":             # <<<<<<<<<<<<<< 
 *     exit(unittest.main ())
 */
  __pyx_2 = PyObject_RichCompare(__pyx_builtin___name__, __pyx_n___main__, Py_EQ); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = __Pyx_PyObject_IsTrue(__pyx_2); if (unlikely(__pyx_5 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_5) {

    /* "/home/erich/doodles/anagrams/python/bag.py":77
 * 
 * if __name__ == "__main__":
 *     exit(unittest.main ())             # <<<<<<<<<<<<<< 
 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_unittest); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_main); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_1 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_4 = PyObject_Call(__pyx_builtin_exit, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("bag");
}

static char *__pyx_filenames[] = {
  "bag.py",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
    }
    else {
        py_funcname = PyString_FromString(funcname);
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
