# -*-python-*-

Program ('anagrams',
         ['anagrams.d',
          'bag.d',
          'dictionary.d',
          'mpz.d',
          'gmppool.d'],
         DFLAGS = ['-unittest', '-g',
                   '-release'
                   #'-fno-bounds-check'
                   ],
         LIBS = ['gmp'],
         LINKFLAGS = ['-pg'])

Program ('hmph',
         ['hmph.d'],
         )
